title:            itmilos   
description:      "web development i sve ostalo"
logo:             logo.png
disqus_shortname: itmilos
share:            true
dropcap:			true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  http://itmilos.github.io

# Owner/author information
owner:
  name:           Milos Rujevic
  avatar:         itmilos.jpg
  email:          itmios@outlook.com    
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    web development i sve ostalo
  # Social networking links used in footer. Update and remove as you like.
  twitter:        itmilos
  facebook:       itmilos
  github:         itmilos      
  instagram:      itmilos
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+MilošRujević

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-47905293-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: kuća
    url: /
    external: true
  - title: super 
    url: /super
  - title: kategorije
    url: /categories
  - title: o meni
    url: /hvalisanje-o-meni

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Belgrade
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://itmilos.github.io/'
  relativeLinks: 'http://itmilos.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "objavljeno"
        field:
          label: "Objavljeno"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "naziv"
        field:
          label: "naziv"
          element: "text"
          value: "Super naziv!"
      - name: "Opis"
        field:
          element: "tekst"
          label: "Opis"
          placeholder: "Upisi opis"
      - name: "Opis"
        field:
          element: "teks"
          label: "Super naziv"
          placeholder: "Upisi super naziv "
      - name: "modifikovano"
        field:
          element: "tekst"
          label: "Da li je ova strana modifikovana?"
          placeholder: "YYYY-MM-DD"
      - name: "kategorije"
        field:
          element: "multiselect"
          label: "Dodaj kategorije"
          placeholder: "Izaberi kategorije"
          value: personal
          options:
            - name: "O meni"
              value: omeni
            - name: "Projekat"
              value: projekat
            - name: "Interesantno"
              value: interesantno
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tagovi"
        field:
          element: "tekst"
          label: "Tagovi"
          placeholder: "Upisite tagove razdvojene zapetom"
      - name: "imagefeature"
        field:
          element: "Tekst"
          label: "Super slika"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Super?"
          value: false
      - name: "komentari"
        field:
          element: "checkbox"
          label: "komentari"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

